# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='cfedefaultshortcode', max_length=15),
            preserve_default=False,
        ),
    ]
